// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqUK9m77wGiG2yAEFWASC_pMUgBq3qt4E',
    appId: '1:232728949907:web:49732a25ab92bab2200966',
    messagingSenderId: '232728949907',
    projectId: 'cs499inventoryapp',
    authDomain: 'cs499inventoryapp.firebaseapp.com',
    storageBucket: 'cs499inventoryapp.firebasestorage.app',
    measurementId: 'G-9C2KD3KB1G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl0OYnP5hNilrNXp_0-9K0L1zOdyI1HAA',
    appId: '1:232728949907:android:45c8da4262067b59200966',
    messagingSenderId: '232728949907',
    projectId: 'cs499inventoryapp',
    storageBucket: 'cs499inventoryapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADKFE7kE_3DpnK0J3ummSlKYQ0LHWmUZg',
    appId: '1:232728949907:ios:53aa46167b105691200966',
    messagingSenderId: '232728949907',
    projectId: 'cs499inventoryapp',
    storageBucket: 'cs499inventoryapp.firebasestorage.app',
    iosBundleId: 'com.matthew.cs499.cs499FinalMatthewMarsh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADKFE7kE_3DpnK0J3ummSlKYQ0LHWmUZg',
    appId: '1:232728949907:ios:53aa46167b105691200966',
    messagingSenderId: '232728949907',
    projectId: 'cs499inventoryapp',
    storageBucket: 'cs499inventoryapp.firebasestorage.app',
    iosBundleId: 'com.matthew.cs499.cs499FinalMatthewMarsh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqUK9m77wGiG2yAEFWASC_pMUgBq3qt4E',
    appId: '1:232728949907:web:60731dd5181f7610200966',
    messagingSenderId: '232728949907',
    projectId: 'cs499inventoryapp',
    authDomain: 'cs499inventoryapp.firebaseapp.com',
    storageBucket: 'cs499inventoryapp.firebasestorage.app',
    measurementId: 'G-MPXPWXEVVR',
  );

}